name: yo_task_managements
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.10
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.1.1
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  flutter_slidable: ^1.2.0
  flutter_speed_dial: ^5.0.0+1
  fluttericon: ^2.0.0
  get: 4.6.1
  google_fonts: ^2.3.1
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  lottie: ^1.2.2
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  syncfusion_flutter_calendar: ^19.4.54
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
